fix

diff --git a/.github/workflows/github_workflows_conditional-ci.yml b/.github/workflows/github_workflows_conditional-ci.yml
--- a/.github/workflows/github_workflows_conditional-ci.yml
+++ b/.github/workflows/github_workflows_conditional-ci.yml
@@ -6,7 +6,21 @@ on:
 
 jobs:
   test:
-    uses: ./.github/workflows/check-ciok.yml
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Search for 'CIOK' in txt files
+        id: search
+        continue-on-error: true
+        run: |
+          if grep -q 'CIOK' *.txt; then
+            echo "CIOK found."
+          else
+            echo "'CIOK' not found in any txt file." >&2
+            exit 1
+          fi
+    continue-on-error: true
 
   conditional-check:
     needs: test
