fix

diff --git a/.github/workflows/github_workflows_conditional-ci.yml b/.github/workflows/github_workflows_conditional-ci.yml
--- a/.github/workflows/github_workflows_conditional-ci.yml
+++ b/.github/workflows/github_workflows_conditional-ci.yml
@@ -16,18 +16,19 @@ jobs:
         id: search
         run: |
           if grep -q 'CIOK' *.txt; then
+            echo "CIOK found."
             echo "ciok_found=true" >> $GITHUB_OUTPUT
             exit 0
           else
+            echo "'CIOK' not found in any txt file."
             echo "ciok_found=false" >> $GITHUB_OUTPUT
-            exit 0
+            exit 1
           fi
-    continue-on-error: true
 
   conditional-check:
     needs: test
     runs-on: ubuntu-latest
-    if: needs.test.outputs.ciok_found == 'false'
+    if: needs.test.result == 'failure'
     outputs:
       result: ${{ steps.check.outputs.result }}
     steps:
@@ -44,6 +45,7 @@ jobs:
           else
             echo "ci-override label does not exist"
             echo "result=failure" >> $GITHUB_OUTPUT
+            exit 1
           fi
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -52,8 +54,8 @@ jobs:
     needs: [test, conditional-check]
     runs-on: ubuntu-latest
     if: |
-      needs.test.outputs.ciok_found == 'true' ||
-      (needs.test.outputs.ciok_found == 'false' && needs.conditional-check.result == 'success')
+      needs.test.result == 'success' ||
+      (needs.test.result == 'failure' && needs.conditional-check.result == 'success')
     steps:
       - name: Mark pipeline as success
         run: echo "CI passed (either CIOK present or ci-override label present)"
@@ -62,7 +64,7 @@ jobs:
     needs: [test, conditional-check]
     runs-on: ubuntu-latest
     if: |
-      needs.test.outputs.ciok_found == 'false' && needs.conditional-check.result == 'failure'
+      needs.test.result == 'failure' && needs.conditional-check.result == 'failure'
     steps:
       - name: Mark pipeline as failure
         run: |
